
POST http://localhost:4000/graphql
Content-Type: application/json

{"query": "{ __schema { types { name } }}" }

###
POST http://localhost:4001/graphql
Content-Type: application/json

{"query": "{ __schema { types { name } }}" }
